#!/bin/bash
set -xe

if [ -z "${1}" ]; then
	echo "${BASH_SOURCE[0]}: Single argument required (common test repos path)"
	exit 1
fi

REPO="foo"
NAME="Foo"
TARGET="${1}/$REPO"
TMPREPO="$(cd ${1} && pwd )/tmp/$REPO"

rm -rf $TMPREPO
mkdir -p $TMPREPO
mv -f $TARGET ${TMPREPO}_orig
cd $TMPREPO
git init --initial-branch=master .
git config user.name "${NAME}User"
git config user.email "${REPO}@${REPO}"
touch $NAME
git add $NAME
git commit -m"${NAME}"
git config --bool core.bare true
cd -
mkdir -p $1
mv $TMPREPO/.git $TARGET
