#!/usr/bin/env bash

set -e

export BASHLIB="`find $PWD -type d | grep -E '/(bin|lib)$' | xargs -n1 printf "%s:"`"
export PATH="$BASHLIB:$PATH"
source bash+ :std

# Move to test/tmp
TMP="tmp"
source test/teardown

export GIT_EXEC_PATH="$PWD/lib:$(git --exec-path)"
export UPSTREAM="$TMP/upstream"
export OWNER="$TMP/owner"
export COLLAB="$TMP/collab"

mkdir -p "$UPSTREAM" "$OWNER" "$COLLAB"

cp -r test/repo/{foo,bar} "$UPSTREAM/"

# export GIT_SUBREPO_QUIET=1
