#!bash

# This script has been renamed to `.rc`. For now `init` sources `.rc` but we
# are moving away from `init` and towards `.rc`. Eventually this file will go
# away. You are encouraged to switch to `source /path/to/git-subrepo/.rc` in
# your shell startup file.

root_path="$(dirname $BASH_SOURCE)"

cat <<... >&2
***
git-subrepo DEPRECATION WARNING
$root_path/init is changing names to $root_path/.rc
Please adjust your shell startup files
See: https://github.com/ingydotnet/git-subrepo/issues/105
***
...

source "$root_path/.rc"
