#!bash

# This script has been renamed to `.rc`. For now `init` sources `.rc` but we
# are moving away from `init` and towards `.rc`. Eventually this file will go
# away. You are encouraged to switch to `source /path/to/git-subrepo/.rc` in
# your shell startup file.

[[ -n ${ZSH_VERSION-} ]] &&
  GIT_SUBREPO_ROOT="$0" ||
  GIT_SUBREPO_ROOT="$BASH_SOURCE"
GIT_SUBREPO_ROOT="$(dirname $GIT_SUBREPO_ROOT)"

cat <<... >&2
***
git-subrepo DEPRECATION WARNING
$GIT_SUBREPO_ROOT/init is changing names to $GIT_SUBREPO_ROOT/.rc
Please adjust your shell startup files
See: https://github.com/ingydotnet/git-subrepo/issues/105
***
...

source "$GIT_SUBREPO_ROOT/.rc"
