#!bash

# This script has been renamed to `.rc`. For now `init` sources `.rc` but we
# are moving away from `init` and towards `.rc`. Eventually this file will go
# away. You are encouraged to switch to `source /path/to/git-subrepo/.rc` in
# your shell startup file.

source "$(dirname $BASH_SOURCE)/.rc"
