# DO NOT EDIT. This file generated by pkg/bin/generate-completion.pl.

function __fish_git_subrepo_subdirs
    git subrepo status -q
end

complete -c git-subrepo -f
complete -c git-subrepo -n '__fish_use_subcommand' -a 'branch clean clone commit config fetch help init pull push status upgrade version'
complete -c git-subrepo -s h -d 'Show the command summary'
complete -c git-subrepo -l help -d 'Help overview'
complete -c git-subrepo -l version -d 'Print the git-subrepo version number'
complete -c git-subrepo -l all -s a -d 'Perform command on all current subrepos'
complete -c git-subrepo -l ALL -s A -d 'Perform command on all subrepos and subsubrepos'
complete -c git-subrepo -l branch -s b -d 'Specify the upstream branch to push/pull/fetch' -r
complete -c git-subrepo -l edit -s e -d 'Edit commit message'
complete -c git-subrepo -l force -s f -d 'Force certain operations'
complete -c git-subrepo -l fetch -s F -d 'Fetch the upstream content first'
complete -c git-subrepo -l method -s M -d 'Join method: '"'"'merge'"'"' (default) or '"'"'rebase'"'"'' -r
complete -c git-subrepo -l message -s m -d 'Specify a commit message' -r
complete -c git-subrepo -l file -d 'Specify a commit message file' -r
complete -c git-subrepo -l remote -s r -d 'Specify the upstream remote to push/pull/fetch' -r
complete -c git-subrepo -l squash -s s -d 'Squash commits on push'
complete -c git-subrepo -l update -s u -d 'Add the --branch and/or --remote overrides to .gitrepo'
complete -c git-subrepo -l quiet -s q -d 'Show minimal output'
complete -c git-subrepo -l verbose -s v -d 'Show verbose output'
complete -c git-subrepo -l debug -s d -d 'Show the actual commands used'
complete -c git-subrepo -l DEBUG -s x -d 'Turn on -x Bash debugging'
complete -c git-subrepo -n '__fish_git_using_command branch' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command clean' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command commit' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command config' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command fetch' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command pull' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command push' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -n '__fish_git_using_command status' -a '(__fish_git_subrepo_subdirs)'
complete -c git-subrepo -F -n '__fish_git_using_command clone' -a '(__fish_git_remotes)' -d 'Repository to clone from'
