name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # For PRs from forks, checkout the merge commit to avoid branch name conflicts
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
